name: Contribution Snap!
on:
  workflow_dispatch:
  schedule:
    - cron: "55 8 * * *"
jobs:
  snap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run snap
      - uses: actions/upload-artifact@v2
        with:
          name: image-of-the-day
          path: image.jpeg
          retention-days: 365
